# Generated by Django 5.2.7 on 2026-03-16 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorcourse',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursestaught', to='professors_fqiq.professor'),
        ),
    ]
