# Generated by Django 5.2.7 on 2025-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0002_grade_class_evaluation_grade_grading_consistency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='photo',
            field=models.ImageField(blank=True, default='professors_photos/defalt_profile.jpg', null=True, upload_to='professors_photos/'),
        ),
    ]
