# Generated by Django 5.2.7 on 2025-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0003_professor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(blank=True, default='professors_photos/default_profile.jpg', null=True, upload_to='professors_photos/'),
        ),
    ]
