# Generated by Django 5.2.7 on 2025-11-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0010_alter_professor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
