# Generated by Django 5.2.7 on 2026-02-18 23:58

import professors_fqiq.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0011_grade_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(blank=True, default='professors_photos/default.png', null=True, upload_to='professors_photos/', validators=[professors_fqiq.validators.validate_image_size, professors_fqiq.validators.validate_image_format, professors_fqiq.validators.validate_image_dimensions]),
        ),
    ]
