# Generated by Django 5.2.7 on 2026-03-12 01:54

import django.db.models.deletion
import professors_fqiq.models
import professors_fqiq.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0013_alter_professor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='courses',
        ),
        migrations.AlterField(
            model_name='professor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=professors_fqiq.models.Professor.professor_upload_path, validators=[professors_fqiq.validators.validate_image_size, professors_fqiq.validators.validate_image_format, professors_fqiq.validators.validate_image_dimensions]),
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='professors_fqiq.professor')),
            ],
        ),
    ]
