# Generated by Django 5.2.7 on 2026-03-12 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0014_remove_professor_courses_alter_professor_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='professors_fqiq.professor'),
        ),
    ]
