# Generated by Django 5.2.7 on 2026-03-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0015_alter_courses_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(related_name='professors', to='professors_fqiq.course'),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
