# Generated by Django 5.2.7 on 2026-03-12 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors_fqiq', '0016_course_professor_courses_delete_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ciclo',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
